name: hello-world

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types:
      - closed
  workflow_dispatch: # Allows manual trigger

jobs:
  if-merged:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Echo success message
        run: echo "The PR was successfully merged."

  manual-trigger:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Echo hello world
        run: echo "hello world"
