name: hello-world

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - closed
    branches:
      - dev
  workflow_dispatch: # Allows manual trigger

jobs:
  on-merge-to-dev:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Echo hello world
        run: echo "hello world"

  push-to-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Echo hello world
