name: hello-world

on:
  push:
    branches:
      - dev
      - test
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger for the main branch PRs

jobs:
  feature-merge-dev:
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"
  
  feature-merge-test:
    if: github.event_name == 'push' && github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"

  pr-main:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"
    workflow_dispatch: # Allows manual trigger
