name: hello-world

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: macos-14
    steps:
    - run: |
        echo The PR was merged
